version: '3'

services:
  db:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    networks:
      - db
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: 'root',
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/data/db
      - ./init/:/docker-entrypoint-initdb.d/
    command: mongod
  taskserver:
    build: taskserver
    networks:
      - db
    ports:
      - "8000:8000"
networks:
  db:
    driver: bridge
